<?xml version="1.0" encoding="UTF-8"?><testrun name="tests (1)" project="MovieRecord" tests="5" started="5" failures="0" errors="1" ignored="0">
  <testsuite name="tests.TestSwingMovieListEditorView" time="0.694">
    <testcase name="testAdding" classname="tests.TestSwingMovieListEditorView" time="0.595"/>
    <testcase name="testListContents" classname="tests.TestSwingMovieListEditorView" time="0.099"/>
  </testsuite>
  <testsuite name="tests.TestMovie" time="0.009">
    <testcase name="initializationError" classname="tests.TestMovie" time="0.009">
      <error>java.lang.Exception: The @Rule 'thrown' must be public.
	at org.junit.internal.runners.rules.RuleFieldValidator.addError(RuleFieldValidator.java:116)
	at org.junit.internal.runners.rules.RuleFieldValidator.validatePublic(RuleFieldValidator.java:90)
	at org.junit.internal.runners.rules.RuleFieldValidator.validateMember(RuleFieldValidator.java:74)
	at org.junit.internal.runners.rules.RuleFieldValidator.validate(RuleFieldValidator.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.validateFields(BlockJUnit4ClassRunner.java:174)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:105)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:355)
	at org.junit.runners.ParentRunner.&lt;init&gt;(ParentRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.&lt;init&gt;(BlockJUnit4ClassRunner.java:57)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.&lt;init&gt;(JUnit4TestReference.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.&lt;init&gt;(JUnit4TestClassReference.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
  </testsuite>
  <testsuite name="tests.TestGUI" time="0.127">
    <testcase name="testConstructorCallsViewWithListToDisplay" classname="tests.TestGUI" time="0.123"/>
    <testcase name="testAdd" classname="tests.TestGUI" time="0.004"/>
  </testsuite>
</testrun>
