<?xml version="1.0" encoding="UTF-8"?><testrun name="tests (1)" project="MovieRecord" tests="15" started="15" failures="1" errors="0" ignored="0">
  <testsuite name="tests.TestSwingMovieListEditorView" time="1.075">
    <testcase name="testWhenSelectFromTheListFillsTheNameFieldWithTheSelectedMovie" classname="tests.TestSwingMovieListEditorView" time="0.566"/>
    <testcase name="testAdding" classname="tests.TestSwingMovieListEditorView" time="0.211"/>
    <testcase name="testListContents" classname="tests.TestSwingMovieListEditorView" time="0.024"/>
    <testcase name="testUpdate" classname="tests.TestSwingMovieListEditorView" time="0.273"/>
  </testsuite>
  <testsuite name="tests.TestMovie" time="0.008">
    <testcase name="testMovieCantBeConstructedWithANullName" classname="tests.TestMovie" time="0.006"/>
    <testcase name="testMovieCantBeConstructedWithAEmptyName" classname="tests.TestMovie" time="0.0"/>
    <testcase name="testMovieCantBeRenamedWithANullName" classname="tests.TestMovie" time="0.001"/>
    <testcase name="testMovieCantBeRenamedWithAEmptyName" classname="tests.TestMovie" time="0.0"/>
    <testcase name="testRename" classname="tests.TestMovie" time="0.001"/>
  </testsuite>
  <testsuite name="tests.TestGUI" time="0.124">
    <testcase name="testConstructorCallsViewWithListToDisplay" classname="tests.TestGUI" time="0.119"/>
    <testcase name="testAdd" classname="tests.TestGUI" time="0.004"/>
    <testcase name="testWhenMovieIsSelectedCallsSetMovieNameOnViewWithTheNameOfSelectedMovie" classname="tests.TestGUI" time="0.0"/>
    <testcase name="testUpdate" classname="tests.TestGUI" time="0.001"/>
  </testsuite>
  <testsuite name="tests.TestMockito" time="0.017">
    <testcase name="testWhenParameterPassedTwiceWithDifferentValuesReturnTimesTwoWhenCheckingBySecondValue" classname="tests.TestMockito" time="0.017"/>
  </testsuite>
  <testsuite name="tests.TestMovieList" time="0.003">
    <testcase name="test" classname="tests.TestMovieList" time="0.003">
      <failure>java.lang.AssertionError: Expected exception: java.lang.IllegalAccessError
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
  </testsuite>
</testrun>
